### ISSUE TITLE
模型效果

### ISSUE THREAD

**Issue by shellhuang1227** [bofen97/llama3-8b-instruct-text-to-sql#1]
请问您有在哪个数据集上对模型进行评测吗？模型准确度和效果怎么样呢？

**Comment by bofen97** [comment]
具体的细节在 https://huggingface.co/tyfeng1997/llama3-8b-instruct-text-to-sql 这里， 是在[b-mc2/sql-create-context](https://huggingface.co/datasets/b-mc2/sql-create-context) 这个数据集上进行的微调，只用了一小部分数据。训练了3轮，top1 精确度是79.90% ，这是我尝试llama3指令版本的实验demo，有很多训练使用的超参数都是用的默认值。

**Comment by shellhuang1227** [comment]
那请问是用哪个微调项目进行的呢？您有用LLaMA Factory吗？

**Comment by bofen97** [comment]
这个代码里面只用了 huggingface的软件栈 没有使用llama factory，用llama factory来做的话会更容易。
